repository: "http://bill:10080/docker/snapcast.git"

jobs:

#start x86 ubuntu xenia images 

  - title: docker_snapcast_client_x86
    type: docker
    arch: x86
    dockerfile: DockerfileClientX86
    description: "Docker Snapcast Client Image with plugins"
    imagename: "bill:5043/audiostation/snapcast-client:$SNAPCASTVERSION"
    buildparameter:
      - type: string
        name: SNAPCASTVERSION
        description: ""
        defaultValue: 0.10.0    

  - title: docker_snapcast_server_x86
    type: docker
    arch: x86
    dockerfile: DockerfileServerX86
    description: "Docker Snapcast Server Image with plugins"
    imagename: "bill:5043/audiostation/snapcast-server:$SNAPCASTVERSION"
    buildparameter:
      - type: string
        name: SNAPCASTVERSION
        description: ""
        defaultValue: 0.10.0
        
  - title: docker_snapcast_client_armhf
    type: docker
    arch: armhf
    dockerfile: DockerfileClientRPI
    description: "Docker Snapcast Client Image with plugins"
    imagename: "bill:5043/audiostation/armhf-snapcast-client:$SNAPCASTVERSION"
    buildparameter:
      - type: string
        name: SNAPCASTVERSION
        description: ""
        defaultValue: 0.10.0    

  - title: docker_snapcast_server_armhf
    type: docker
    arch: armhf
    dockerfile: DockerfileServerRPI
    description: "Docker Snapcast Server Image with plugins"
    imagename: "bill:5043/audiostation/armhf-snapcast-server:$SNAPCASTVERSION"
    buildparameter:
      - type: string
        name: SNAPCASTVERSION
        description: ""
        defaultValue: 0.10.0              