snapserver:
  build: ../.
  dockerfile: DockerfileServerRPI
  command: "/usr/sbin/snapserver"

snapclient:
  build: ../.
  dockerfile: DockerfileClientRPI
  links:
   - snapserver:snapserverhost
  devices:
   - "/dev/snd/:/dev/snd/"
  command: "/usr/sbin/snapclient -i snapserverhost"
  