snapserver:
  build: ../.
  dockerfile: DockerfileServerRPI

snapclient:
  build: ../.
  dockerfile: DockerfileClientRPI
  links:
   - snapserver:snapserverhost
  devices:
   - "/dev/snd/:/dev/snd/"
  command: "-i snapserverhost"
  
